FROM golang

ENV SERVICE_STAGE=dev_stage

WORKDIR /usr/src/backend

COPY go.mod go.sum ./

RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY . .

CMD [ "/go/bin/air", "-c", ".air.toml" ]
